### ISSUE TITLE
Структура проекта 

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#1]
Тут в основном структура делится на страницы и компоненты, может еще  шрифты и сторонние стили или код, цвета) В компонентах должны лежать отдельные сущности со своими разметкой, стилями, кодом (pug, scss, js) еще может картинки его. В одном компоненте должен лежать сам компонент и больше не какой другой. Страницы похожи на компоненты тем что в них тоже должны лежать стили разметка и код который к ним относится. Отличаются тем что компоненты можно переиспользовать на разных страницах.

**Comment by DaRkLoL1** [comment]
тест тут зачем?)

**Comment by DaRkLoL1** [comment]
index.html тебе зачем? почему favicon прост валяется в src? в util файл libs пустой? и саму папку вытащи из scss
postcss.config.js не в главной папке должен лежать?
в компонентах у тебя есть 3 папки их нужно удалить и вынести все компоненты, в header и footer почему в одной папке? 
и в pages зачем ты разделяешь на разные стили, у тебя должно быть один файл со всеми стилями страницы или выделяй в компоненты)

**Comment by DaRkLoL1** [comment]
![Скриншот 12-05-2020 17_01_36](https://user-images.githubusercontent.com/32780725/81701143-48654380-9472-11ea-8592-35e0047e4e99.png)
картинка должна лежать в папке image

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_34_09 (1)](https://user-images.githubusercontent.com/32780725/82231721-3bdf6000-9936-11ea-9bda-260f86315d36.png)
а почему у тебя 2 миксина в одном компоненте, их нужно вынести по разным папкам или как то объединить

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_35_54](https://user-images.githubusercontent.com/32780725/82231845-71844900-9936-11ea-8ae9-e03e1dfd6bc2.png)
стили разметку и код библиотек нужно вынести в отдельную папку рядом с page и component, назвать можешь vendors например

**Comment by DaRkLoL1** [comment]
все повторяющиеся картинки на разных страницах или компонентах лучше вынести в папку например images в src/

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 15_56_48](https://user-images.githubusercontent.com/32780725/82561254-bcdb6900-9b7b-11ea-814d-4aadc438695b.png)
темплайт пейдж вынеси в компоненты

**Comment by skinnynpale** [comment]
Хорошо, можешь закрыть ишью
