### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#11]
Сейчас каждый компонент написан функцией, которая в некоторых случаях(к примеру с dropdown.js) получается довольно громоздкой. Это всё лучше заменить на js-классы, чтобы потом уже для каждого найденного по селектору элемента создавать свой инстанс. Такой подход позволит разделить функционал по методам и сделать код более читаемым.

Также надобности в iife для ограничения видимости особо не будет, т.к. всё будет в пределах класса. Кстати вызов и создание инстансов надо сделать отдельно - рядом положить файл init.js, например. Чтобы если ты захотел этот класс импортировать и переиспользовать в другом компоненте тебе не пришлось бы убирать эти вызовы.

**Comment by DaRkLoL1** [comment]
![Скриншот 16-05-2020 12_20_45 (1)](https://user-images.githubusercontent.com/32780725/82116100-b611b800-976f-11ea-86a9-c9cf39bbb1cd.png)
Не использовать id, https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md 10 пункт 
Вдруг тебе потребуется много элементов создать используй для этого классы,
 import { Dropdown } from './Dropdown';

const arrDropdown = document.querySelectorAll('.js-dropdown');
arrDropdown.forEach((item, index) => {
  new Dropdown(item, index);
});
вот так например. нужно было создать в компоненте файл инициации класса и передавать туда селектор класса. И у тебя не везде в классы переделано еще)

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 19_11_37 (1)](https://user-images.githubusercontent.com/32780725/82235645-a5ae3880-993b-11ea-86d5-dd51df287ec2.png)
не нужно создавать в jQuery плагины, прост разбей эту функциональность на методы и добавь в класс

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 19_15_56](https://user-images.githubusercontent.com/32780725/82235940-0e95b080-993c-11ea-94ee-1aeb1b00e5a8.png)
а зачем ты добавляешь методы в объект, а не создаешь в прототипе

**Comment by DaRkLoL1** [comment]
да кстати поиск элементов и добавление обработчиков событий должны лежать в разных методах

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 19_20_07](https://user-images.githubusercontent.com/32780725/82236404-b7441000-993c-11ea-970d-359b1c76ea96.png)
а зачем ты оборачиваешь в  функцию, разве без нее работать не будет?

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_33_48](https://user-images.githubusercontent.com/32780725/82564101-de8b1f00-9b80-11ea-9187-ba6752e868d8.png)
а зачем ты вызываешь функцию findElement почему сразу не обернуть в $() и имя переменной jQuery элементов должно начинаться с $ у тебя будет тогда this.$container

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_39_56](https://user-images.githubusercontent.com/32780725/82564899-3bd3a000-9b82-11ea-87e7-4e2a4328ad21.png)
а почему ты тут ищешь элемент а потом добавляешь элемент, я же писал что нужно поиск элементов выделять в отдельный метод нужно эти элементы находить и желательно добавлять в поля класса

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_50_48](https://user-images.githubusercontent.com/32780725/82565747-95889a00-9b83-11ea-9edf-0f5b74d3d299.png)
при нажатии кнопки применить у дата фильтр возникает ошибка
у datadropdown тоже ошибка

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 17_00_51](https://user-images.githubusercontent.com/32780725/82566509-af76ac80-9b84-11ea-8e52-b42db13b8d65.png)
присвоение обработчиков тоже в отдельный метод

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/83281578-7ed8e780-a202-11ea-9e29-16dc6024bff6.png)

Зачем здесь if ?

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/83281925-0888b500-a203-11ea-9db8-80fac74a547a.png)

Сделать значение по дефолту

**Comment by skinnynpale** [comment]
Хорошо, можешь закрывать

**Comment by skinnynpale** [comment]
А еще исправь чтобы можно было по нажатию на название открывать лист
![image](https://user-images.githubusercontent.com/52371356/83320722-5be71b80-a274-11ea-93c1-52d20e216c44.png)

**Comment by skinnynpale** [comment]
Повесь еще cursor: pointer и можешь закрывать

**Comment by Fr0stmourne** [comment]
[add cursor: pointer](https://github.com/Fr0stmourne/fsd-ui-kit/commit/4e43424e5ee77ff5a2ca8dc8fb398437a4b1fe35)
