### ISSUE TITLE
Кодстайл

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#13]
При передаче в качестве аргумента объекта со множеством ключей целесообразнее отбивать каждый новый ключ переносом строки в целях увеличения читаемости кода. Посмотри и исправь плиз и в других местах проекта
![Скриншот 12-05-2020 17_00_20](https://user-images.githubusercontent.com/32780725/81701076-2ff52900-9472-11ea-8f9c-47afe3a83b8f.png)

**Comment by DaRkLoL1** [comment]
Классы в стилях лучше для отделения Блока от Элемента использовать __ 2 нижних подчеркивания, а для Блока от Модификатора или Элемента от Модификатора лучше _ 1 нижнее подчеркивание)

**Comment by DaRkLoL1** [comment]
![Скриншот 16-05-2020 12_48_05](https://user-images.githubusercontent.com/32780725/82116578-882e7280-9773-11ea-8457-898259c80153.png)
![Скриншот 16-05-2020 12_47_47](https://user-images.githubusercontent.com/32780725/82116583-8d8bbd00-9773-11ea-9e00-b138a3a1936a.png)
лишние переносы строк  между св-ва они не нужны, между соседними правилами 1 перенос
между родителем и 1 и между родителем и  последним правилом не должно быть переносов

**Comment by DaRkLoL1** [comment]
![Скриншот 16-05-2020 12_52_09](https://user-images.githubusercontent.com/32780725/82116663-1b67a800-9774-11ea-9677-72ce67a4fb8a.png)
а почему для title дефолт значение не задал?

**Comment by DaRkLoL1** [comment]
![Скриншот 16-05-2020 12_53_25](https://user-images.githubusercontent.com/32780725/82116682-3fc38480-9774-11ea-845c-bd3e91366755.png)
в css должно быть 2 пробела а у тебя 4

**Comment by DaRkLoL1** [comment]
![Скриншот 16-05-2020 12_55_01](https://user-images.githubusercontent.com/32780725/82116732-8618e380-9774-11ea-8a79-38ba5109d3ca.png)
а зачем там проверка items.length ты можешь поставить ['There are no items'] как дефолтный параметр

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 15_48_12](https://user-images.githubusercontent.com/32780725/82560658-87824b80-9b7a-11ea-8681-f3cc8c7ec3d1.png)
В Pug можно использовать только двойные кавычки если это не шаблонные выражения

**Comment by skinnynpale** [comment]
Можешь закрывать
