### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#14]
![Скриншот 16-05-2020 12_31_05](https://user-images.githubusercontent.com/32780725/82116270-3d136000-9771-11ea-86a2-71cd1abc2256.png)
Почему у тебя wrapper не элемент signin-page, у тебя для кажной страницы должен быть как бы 1 блок, и от него строиться элементы, типа создается пространство имен, чтобы какой нить другой класс случайно не переписал.
![Скриншот 16-05-2020 12_35_48](https://user-images.githubusercontent.com/32780725/82116350-d0e52c00-9771-11ea-9a1a-d181aac16f7a.png) здесь тоже самое room-photos container  room-info должны были быть элементами room-details

**Comment by DaRkLoL1** [comment]
![Скриншот 16-05-2020 12_40_19](https://user-images.githubusercontent.com/32780725/82116429-79938b80-9772-11ea-999b-0664156c18db.png)
нельзя переопределять селекторы класса компонента снаружи компонента, если хочешь задать внешнюю геометрию создай обертку. 
margin-left: -3px; для маржинов запрещено использовать отрицательные значения 
!important тоже запрещен 
main img селекторы по тегу тоже запрещены

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_38_42](https://user-images.githubusercontent.com/32780725/82232152-e5beec80-9936-11ea-8302-7a0cf6d6c557.png)
я же писал что не нужно переопределять стили компонента где то в другом месте

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_46_51](https://user-images.githubusercontent.com/32780725/82233573-e6588280-9938-11ea-8651-fa708fef89c0.png)
нашел блок внутри другого блока, я же выше писал так не делать, лучше сразу проверять ошибки по всему проекту , а не только где я указал, так я быстрее все проверю))

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 19_00_01](https://user-images.githubusercontent.com/32780725/82234246-d42b1400-9939-11ea-9bcd-cb776e5e60d8.png)
лишний блок и микс

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 15_44_09](https://user-images.githubusercontent.com/32780725/82560374-05922280-9b7a-11ea-94b9-90392f428912.png)
опять меняешь стили компонентов снаружи( *::placeholder {}

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_23_10](https://user-images.githubusercontent.com/32780725/82563307-81429e00-9b7f-11ea-8dd2-36ccb1b3fff4.png)
![Скриншот 21-05-2020 15_54_12](https://user-images.githubusercontent.com/32780725/82561054-59e9d200-9b7b-11ea-97d1-1a3891b191b4.png)

Не двигать элемент при помощи top, left, right или bottom при position: relative, где это можно заменить другими подходами;

можно использовать сам position: relative (без свойств top, left, right или bottom) для z-index и для того, чтобы указать потомкам элемента ориентир.

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_02_20](https://user-images.githubusercontent.com/32780725/82561747-8c47ff00-9b7c-11ea-999b-aacd62221dd3.png)
удали неиспользуемый код

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_03_35](https://user-images.githubusercontent.com/32780725/82561940-f365b380-9b7c-11ea-92c2-1109c9a34ca8.png)

Всегда использовать как минимум один запасной шрифт и одно запасное семейство;

Их перечисляют через запятую в font-family, так что каждое использование font-family должно происходить по схеме: font-family: Helvetica, Arial, sans-serif;

Здесь Helvetica — нестандартный подключаемый шрифт.

Arial — стандартный шрифт, который используется почти на всех клиентах, он будет использоваться, если не удалось подключить Helvetica.

sans-serif — это семейство всех шрифтов без засечек (каковыми являются и Helvetica, и Arial). Если даже Arial-а на компе нет, то поставится какой-то системный дефолтный шрифт без засечек. Выбор здесь надо делать из "serif," "sans-serif," или "monospace". Для шрифтов без засечек использовать по умолчанию Arial, для шрифтов с засечками — Georgia (а не Times New Roman), а для моноширинных — "Courier New"

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 16_21_07](https://user-images.githubusercontent.com/32780725/82563124-1f823400-9b7f-11ea-9f57-9847d7dc3a86.png)
![Скриншот 21-05-2020 16_26_47](https://user-images.githubusercontent.com/32780725/82563529-ed250680-9b7f-11ea-8238-d80f8af25a63.png)

у тебя у  последнего элемента item будет вылазить маргин через родителя. Проверь везде

**Comment by skinnynpale** [comment]
Можешь закрывать
