### ISSUE TITLE
Наименование 

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#15]
![Скриншот 16-05-2020 12_57_42 (1)](https://user-images.githubusercontent.com/32780725/82116811-f9225a00-9774-11ea-914f-3f7877700e28.png)
названия модификаторов неправильное, одиночный мод. следует использовать для boolean значения, там clicked hovered focused когда значение не важно, тут же думаю должно быть блок_имя-мод_значение
да и называть ты должен блок_существительное_прилагательное или если булл мод блок_глагол-прошедшей-формы) да и почему type без дефолт значения хотя бы "" поставил, чтобы я не искал какой тип данных там лежит) ну правда тут сразу видно, но если кода много придется поискать))

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_41_12](https://user-images.githubusercontent.com/32780725/82232362-346c8680-9937-11ea-8e85-62b6f88c387f.png)
имя элемента или блока  должно отражать сущность класса, а не его порядковый номер или расположение на странице, если потребуется элемент куда то перенести то придется менять имя

**Comment by DaRkLoL1** [comment]
.ui-kit__more-dropdowns странное имя класса больше чего?
.headers-footers__header_unlogged
.headers-footers__header_logged
.headers-footers__footer_extended
.headers-footers__footer_non-extended похоже ты ошибся поставив здесь модификаторы)

**Comment by DaRkLoL1** [comment]
и файлы классов переименуй например DateFilter, а к init добавь префикс date-filter-init

**Comment by skinnynpale** [comment]
Можешь закрывать
