### ISSUE TITLE
Навигация по сайту 

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#16]
В твоем проекте при клике на кнопки "Войти", "Зарегистрироваться", "Подобрать номер" ничего не происходит, хотя макетом предусмотрены отдельные страницы под эти действия, т.е. по идее эти кнопки должны быть ссылками на другие страницы сайта.

Было бы круто еще при нажатии на эту карточку реализовать переход на страницу **Room details**, таким образом навигация покрыла бы все страницы сайта, но это по желанию, думаю )
![5](https://user-images.githubusercontent.com/19621113/69803140-4e30da80-11ec-11ea-91ac-a4da6b879a36.png)

**Comment by DaRkLoL1** [comment]
![6](https://user-images.githubusercontent.com/19621113/69803671-cea40b00-11ed-11ea-82c1-955ce849318c.png)
Эти кнопки - не просто элемент декора, они предназначены для перехода на соответствующие аккаунты в соцсетях и поэтому тоже должны быть реализованы ссылками

**Comment by DaRkLoL1** [comment]
![1](https://user-images.githubusercontent.com/19621113/71061414-fc3efd00-2178-11ea-9c26-6cc45885691b.png)
На данный момент в проекте отсутствует возможность быстрого перехода на главную страницу с внутренних страниц сайта. По идее вот этот логотип должен быть ссылкой на главную

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_21_29](https://user-images.githubusercontent.com/32780725/82230471-71834980-9934-11ea-92dc-0787c74fa8bc.png)
это должна быть кнопка типа submit

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_22_49](https://user-images.githubusercontent.com/32780725/82230620-a2fc1500-9934-11ea-92f2-d714fbcd81a9.png)
кнопка создать должна переходить на регистрацию

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_24_00](https://user-images.githubusercontent.com/32780725/82230733-cde66900-9934-11ea-8b65-495d6346765e.png)
кнопка войти должна переходить на вход

**Comment by DaRkLoL1** [comment]
![Скриншот 18-05-2020 18_26_34](https://user-images.githubusercontent.com/32780725/82230968-2158b700-9935-11ea-8459-65b4e9762aa5.png)
Ссылки на чужие сайты должны содержать атрибут target="_blank", чтобы открываться в новом окне;

Все ссылки с target="_blank" должны так же содержать атрибут rel="noopener noreferrer", это связано с уязвимостью:

Это связано с уязвимостью, в соответствии с которой сайт, который вы открыли, получит доступ к сайту, с которого перешли через window.opener, причем это работает даже кроссдоменно.

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 15_34_11](https://user-images.githubusercontent.com/32780725/82559586-91a34a80-9b78-11ea-9f69-5e3a06f5cb9d.png)
кнопки войти и создать нужно было оставить ссылкой а переделать в button submit только подобрать номер)

**Comment by skinnynpale** [comment]
Можешь закрывать
