### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-ui-kit#37]
1. Достаточно добавлять класс c js-префиксом на блок, выбирать блок по этому классу, а внутри блока работать с классами без префикса. По всему проекту.
![one js-](https://user-images.githubusercontent.com/51824674/86332351-3b8fef80-bc6c-11ea-99b8-7235ebf15b51.png)

2. 
![Screenshot from 2020-07-02 14-00-34](https://user-images.githubusercontent.com/51824674/86332516-7134d880-bc6c-11ea-8d05-bc8d1d1810b2.png)
Инициализируй все в одном методе.
![lightweight](https://user-images.githubusercontent.com/51824674/86332654-a2150d80-bc6c-11ea-904c-69ffff60ca76.png)

**Comment by Fr0stmourne** [comment]
Исправил
