### ISSUE TITLE
БЭМ, Компонентность

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-ui-kit#38]
1. Убрать хардкод из миксинов, оставить только переменные
![hardcode](https://user-images.githubusercontent.com/51824674/86332874-ec968a00-bc6c-11ea-87b7-dc43e9fd2f84.png)
2. Здесь используй модификатор ключ-значение, только ключ не dark, как было, а что-то типа background-color
![key-value](https://user-images.githubusercontent.com/51824674/86332991-194aa180-bc6d-11ea-98f4-209734917471.png)

**Comment by Fr0stmourne** [comment]
Исправил

**Comment by iatsdotfatr** [comment]
1. Не надо добавлять лишние классы, которые в рамках бэм являются отдельными блоками, работай в js с бэм-классами, по всему проекту.
![blocks](https://user-images.githubusercontent.com/51824674/86609138-4ed4ef00-bfcd-11ea-9c98-8aaa546cc273.png)

2. Здесь тоже получается два бэм-блока в одном миксине, или сделать элементами, или вынести в отдельный миксин
![two blocks](https://user-images.githubusercontent.com/51824674/86609274-90659a00-bfcd-11ea-8ecf-3ee20c90ea74.png)

3. В одном файле один миксин, можно в папке pagination папку page или components/page (две папки) и там оформить page как отдельный бэм-блок.
![Screenshot from 2020-07-06 20-47-13](https://user-images.githubusercontent.com/51824674/86609640-02d67a00-bfce-11ea-81af-b2bfd0fe0c4a.png)

4. Внешнее позиционирование блока.
![block positioning](https://user-images.githubusercontent.com/51824674/86609689-1bdf2b00-bfce-11ea-8698-55445e2a23d0.png)

5. Title где-то используется? Если да, то неправильно, если нет, тогда он не нужен.
![do you use](https://user-images.githubusercontent.com/51824674/86609759-374a3600-bfce-11ea-9744-9c1cd57a456c.png)

6. Хардкод остался здесь, и еще минимум в трех местах
![Screenshot from 2020-07-06 20-15-09](https://user-images.githubusercontent.com/51824674/86609820-4c26c980-bfce-11ea-987a-14b1e704d233.png)

**Comment by Fr0stmourne** [comment]
Вроде всё исправил, можно проверять

**Comment by iatsdotfatr** [comment]
1. Внешнее позиционирование все еще присутствует.
![Screenshot from 2020-07-09 19-25-48](https://user-images.githubusercontent.com/51824674/87045883-39a0d000-c21a-11ea-9909-aac9f23a5452.png)

2. Все страницы также сделай отдельными миксинами, в которые передавай данные для всех вложенных миксинов вне зависимости от уровня вложенности, то есть, например, в миксин для search-room должны передаваться данные для вложенных в него чекбоксов, дропдаунов и т.д. Возможно, имеет смысл вынести хедер и футер в общий шаблон страницы, а в миксины делать только для содержимого между ними.

**Comment by Fr0stmourne** [comment]
Готово, можно проверять
