### ISSUE TITLE
Разное

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-ui-kit#39]
Не стоит использовать сокращения, даже те, которые кажутся очевидными. По всему проекту.
![shortening1](https://user-images.githubusercontent.com/51824674/86333148-51ea7b00-bc6d-11ea-9542-3a7e0ddfe4b7.png)
![shortening](https://user-images.githubusercontent.com/51824674/86333169-59118900-bc6d-11ea-8a61-5179d0f9f8f3.png)

**Comment by Fr0stmourne** [comment]
Вроде исправил, оставил только общепринятые типа img/nav
