### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-ui-kit#40]
1. Sign in, Registration
![sign in](https://user-images.githubusercontent.com/51824674/87283489-2a21cf80-c517-11ea-8568-b98628e8b6ad.png)
![reg page](https://user-images.githubusercontent.com/51824674/87283499-2beb9300-c517-11ea-9b4a-05a1a8dc5bda.png)

2. Заголовок слайдера
![fix](https://user-images.githubusercontent.com/51824674/87283587-41f95380-c517-11ea-92da-7055e2af0175.png)
![filter](https://user-images.githubusercontent.com/51824674/87283591-432a8080-c517-11ea-9d98-40893e530701.png)

**Comment by Fr0stmourne** [comment]
А как это воспроизвести? У меня вмещается на одной строчке
![image](https://user-images.githubusercontent.com/46089168/87308710-4710cf80-c524-11ea-9e85-43993171ab9a.png)
![image](https://user-images.githubusercontent.com/46089168/87308834-7cb5b880-c524-11ea-9fce-422035c74966.png)

**Comment by Fr0stmourne** [comment]
Попробовал пофиксить заголовок, не знаю, вышло или нет. Остальное вроде сделал, можешь смотреть

**Comment by iatsdotfatr** [comment]
Registration и sign in все еще съезжают, если у тебя нормально, то оставь, как есть и обнови демо-страницы, я на другой ОС посмотрю, там же посмотрю заголовок, на линуксе ему места не хватает из-за ширины инпута, если инпут нельзя заменить на другой элемент из-за плагина, то тоже ничего не делай.

**Comment by Fr0stmourne** [comment]
Демка автоматически обновляется после коммитов, по ней сейчас сравнил, у меня вот так выглядит
![image](https://user-images.githubusercontent.com/46089168/87543427-67b86100-c6ad-11ea-9ac3-b2b11ae0691d.png)
![image](https://user-images.githubusercontent.com/46089168/87543532-98989600-c6ad-11ea-8682-614e35ec897c.png)

**Comment by Fr0stmourne** [comment]
Заменил инпут в слайдере на обычный span, надеюсь, теперь на линуксе тоже будет ок. Инпут совсем убирать не стал, оставил скрытым, чтобы форма корректно обрабатывалась
