### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by iatsdotfatr** [Fr0stmourne/fsd-ui-kit#41]
1. На мобильном такие отступы не нужны, оставить примерно столько же, сколько на лэндинге сверху, также текст на лэндинге не скрывать, а отображать снизу карточки.
![less margin](https://user-images.githubusercontent.com/51824674/87284438-322e3f00-c518-11ea-8cf9-2bca7465bda6.png)
![margins](https://user-images.githubusercontent.com/51824674/87284439-32c6d580-c518-11ea-864f-ee4161e29cbd.png)

2. На мобильном hover не работает, приходится нажимать, хотя бы поэтому (и не поэтому тоже) надо запретить переход по ссылке
![touch](https://user-images.githubusercontent.com/51824674/87284863-ac5ec380-c518-11ea-891b-8c2877ef7531.png)

3. Слишком близко
![to close](https://user-images.githubusercontent.com/51824674/87284994-d1ebcd00-c518-11ea-9a23-9a8db6661cc7.png)
![cllose](https://user-images.githubusercontent.com/51824674/87285002-d3b59080-c518-11ea-9f35-7aa0001b6753.png)
![closse](https://user-images.githubusercontent.com/51824674/87285011-d4e6bd80-c518-11ea-840a-732ddb323f4f.png)

4. Отступ между блоками сделать больше
![more margin](https://user-images.githubusercontent.com/51824674/87285581-7b32c300-c519-11ea-9eae-dd4d0414679b.png)

5. Выравнивать блок с заголовком по центру, пагинацию центрировать по блоку.
![Screenshot from 2020-07-13 12-59-44](https://user-images.githubusercontent.com/51824674/87285890-ea101c00-c519-11ea-95fe-1427b8575fd9.png)

**Comment by Fr0stmourne** [comment]
Вроде всё поправил, можешь проверять

**Comment by iatsdotfatr** [comment]
1. Под скролл заходит
![nopadding](https://user-images.githubusercontent.com/51824674/87545618-11a5e680-c6ca-11ea-9b02-6dac9a7a7875.png)

2. Синхронизируй контейнеры хедера и футера
![containers](https://user-images.githubusercontent.com/51824674/87545658-23878980-c6ca-11ea-9f99-e44a7c783b64.png)

3. Маска скрывается
![texxt](https://user-images.githubusercontent.com/51824674/87545767-56ca1880-c6ca-11ea-8657-129912771d7f.png)

**Comment by Fr0stmourne** [comment]
1. Это не devtools в хроме? И на каком разрешении такое? У меня такого нет, как это воспроизвести?
![image](https://user-images.githubusercontent.com/46089168/87546301-0050e000-c6b2-11ea-9cff-5586b388e2a0.png)

**Comment by iatsdotfatr** [comment]
Это до того, как колонка под меню уходит
![Screenshot from 2020-07-15 18-51-27](https://user-images.githubusercontent.com/51824674/87547005-474bcf00-c6cc-11ea-893a-62be2b2e0da9.png)

**Comment by Fr0stmourne** [comment]
У меня так и не получилось воспроизвести, вот видео. Это надо не через devtools смотреть?



[screencast-nimbus-capture-2020.07.15-15_58_25.zip](https://github.com/Fr0stmourne/fsd-ui-kit/files/4925378/screencast-nimbus-capture-2020.07.15-15_58_25.zip)

**Comment by iatsdotfatr** [comment]
Просто уменьши размер браузера или открой консоль сбоку экрана и растяни. На линуксе заходит больше, на винде на firefox меньше, на chrome просто прижимается вплотную, как будто стоит что-то вроде правила overflow: overlay.

**Comment by Fr0stmourne** [comment]
Вроде исправил, в firefox не налезает у меня теперь, остальное тоже сделал

[3ea273e](https://github.com/Fr0stmourne/fsd-ui-kit/commit/3ea273e639386e18a4314fe05778fb119348dd2b)
[b64f202](https://github.com/Fr0stmourne/fsd-ui-kit/commit/b64f20283f62f73d6cf8aa014083963dd441347d)
[499abd8](https://github.com/Fr0stmourne/fsd-ui-kit/commit/499abd8d9c2885da00a5ac370a56e9bf4005d394)

**Comment by iatsdotfatr** [comment]
1. Перенос происходит поздно и не очень.
![Screenshot from 2020-07-20 21-38-56](https://user-images.githubusercontent.com/51824674/87957875-a8abdd80-cad2-11ea-80b2-6b6e64440201.png)
![Screenshot from 2020-07-20 21-36-51](https://user-images.githubusercontent.com/51824674/87957881-a9dd0a80-cad2-11ea-95d8-dc5f7f07c355.png)

2. В меню нет иконок у дропдаунов и дропдауны кликаются.
![Peek 2020-07-20 21-46](https://user-images.githubusercontent.com/51824674/87958030-d7c24f00-cad2-11ea-98b6-e413092f69d0.gif)

**Comment by Fr0stmourne** [comment]
Всё исправил

1. У меня не воспроизвелось, но по идее поправил, добавив отступ, а перенос теперь по тире
