### ISSUE TITLE
Date Dropdown

### ISSUE THREAD

**Issue by DaRkLoL1** [Fr0stmourne/fsd-ui-kit#8]
![Скриншот 07-05-2020 19_09_17](https://user-images.githubusercontent.com/32780725/81318022-45470d80-9096-11ea-8f19-cfaf5ea4aef5.png)
У тебя походу создается два календаря, я не могу выбрать диапазон на календаре
и уголка не должно быть

**Comment by DaRkLoL1** [comment]
![Скриншот 21-05-2020 170417](https://user-images.githubusercontent.com/32780725/82567123-9e7a6b00-9b85-11ea-95ae-ddad8a1aa033.png)
![Скриншот 21-05-2020 170441](https://user-images.githubusercontent.com/32780725/82567126-a0442e80-9b85-11ea-8b01-8ead372a2c66.png)
у тебя создаются два календаря, я же просил оставить только один. При нажатии кнопки применить возникает ошибка. И при выделении вокруг сегодняшнего числа полностью не закрашивается область.

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/83280801-53a1c880-a201-11ea-9f2b-9746fb3c435a.png)

Починить стиль там где цифра 19

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/83284194-99ad5b00-a206-11ea-8c19-a4821d9a294b.png)

Пофиксить стиль рамки, см Figma

**Comment by skinnynpale** [comment]
Хорошо, можешь закрывать
